<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Are you sure you want to delete this item?' => 'Siz dogurdanam pozmak isleýäňizmi?',
  'Delete' => 'Poz',
  'Displaying {start}-{end} of {count} result(s).' => '{count} netijeden {start}-{end} aralyk görkezilýär.',
  'Either "name" or "value" must be specified for CDataColumn.' => 'CDataColumn belgisi üçin "name" ýa-da "value" belli edilmelidir.',
  'Home' => 'Baş sahypa',
  'No results found.' => 'Netije tapylmady.',
  'Not set' => 'Gurnalmadyk',
  'Please specify the "attributes" property.' => 'Haýyş "attributes" belligini belli ediň.',
  'Please specify the "data" property.' => 'Haýyş "data" belligini belli ediň.',
  'Sort by: ' => 'Yzygiderligi: ',
  'The "dataProvider" property cannot be empty.' => '"dataProvider" belligi boş goýulmaz.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Bellik, "Type" we "Label" \'yň optional bolan ýagdaýynda, "Name:Type:Label" görnüşinde belli ediler.',
  'The button type "{type}" is not supported.' => '"{type}" görnüşi laýyk gelenok.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Sütün, "Type" ve "Label" \'yň optionla bolan wagtynda, "Name:Type:Label" görnüşinde belli edilmelidir.',
  'The property "itemView" cannot be empty.' => '"itemView" belligi boş goýulmaz.',
  'Total {count} result(s).' => 'Jemi netije: {count}.',
  'Update' => 'Täzele',
  'View' => 'Görkez',
  '{class} must specify "model" and "attribute" or "name" property values.' => '{class} üçin "model" we "attribute" ýa-da "name" bellikleri belli edilmelidir.',
);
